Repository JoseDiazCodes/DiversityCodes, pull requests merged in 2024-02, with the labels that each got.

#4 added and refractored the code
  .env
  .gitignore
  README.md
  client/public/admin.html
  client/public/index.html
  client/public/viewExam.html
  client/src/App.js
  package-lock.json
Labels: enhancement

#32 Made Admin Panel look better...
  client/client/src/index.css
  client/client/tailwind.config.js
  client/components.json
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/@/components/ui/button.jsx
  client/src/@/components/ui/form.jsx
  client/src/@/components/ui/label.jsx
  client/src/@/components/ui/navigation-menu.jsx
  client/src/@/lib/utils.js
  client/src/App.js
  client/src/components/NavBar.js
  client/src/index.css
  client/src/pages/Admin.js
  client/tailwind.config.js
Labels: enhancement

#43 Updated the home page styling to match Exam and admin
  client/src/pages/Home.js
Labels: enhancement

#44 Search bar implemented in Exam view
  client/src/pages/ExamView.js
  client/src/pages/Home.js
Labels: enhancement

#45 Create new Exam enhanced
  client/src/components/NavBar.js
  client/src/pages/Admin.js
  client/src/pages/ExamView.js
  client/src/pages/Home.js
Labels: enhancement

#58 added details page for exam-id
  client/src/App.css
  client/src/App.js
  client/src/components/SingleExamView.js
  client/src/components/SinglePatientView.js
  client/src/pages/ExamView.js
  server/controllers/controllers/exam.js
  server/controllers/controllers/user-controller.js
  server/routes/routes/exams.js
  server/routes/routes/index.js
  server/routes/routes/users.js
Labels: enhancement

#60 redesigned home page
  client/src/App.css
  client/src/pages/Home.js
Labels: enhancement

#128 Delete confimation
  client/src/pages/ExamView.js
Labels: enhancement

#129 changed the update controller
  server/controllers/exam.js
  server/routes/exams.js
Labels: bug

#133 Styling for SinglePatientView and SingleExamView
  client/package-lock.json
  client/package.json
  client/src/components/SingleExamView.js
  client/src/components/SinglePatientView.js
  client/src/components/UpdateExam.js
Labels: enhancement, front-end

#134 Removed the second back button
  client/src/components/SinglePatientView.js
Labels: duplicate

#139 Yonas update
  client/src/components/UpdateExam.js
  client/src/pages/ExamView.js
Labels: enhancement

#140 image rendering aws url introduced
  client/src/components/SingleExamView.js
Labels: good first issue

#141 Rendered images with Yonas's code
  client/src/pages/ExamTable.js
Labels: enhancement

#145 image rendered in singelExamView and ExamView page
  client/src/components/SinglePatientView.js
  client/src/pages/ExamView.js
Labels: enhancement

#149 render all images in Admin page
  client/src/pages/ExamView.js
Labels: enhancement

#163 Fixed ExamTable back to prev version
  client/src/pages/ExamTable.js
Labels: front-end
